### ISSUE TITLE
Todo List for Friday

### ISSUE THREAD

**Issue by sohilpandya** [DRDD2016/app#282]
- [ ] Profile Page with edit name and log out 1
- [ ] Tabbed View - (hosting/invited/all) 2
- [ ] swipe to Delete photo (Research to see how feasible it is on web app) 3
- [ ] CSS for RSVP Panel 2
- [ ] Calendar/Album CSS 1
    - [ ] Fetch latest photo from the list so that we can show that to the user and also show who shared it. 1
